language: python
python:
- "2.7"
before_install:
- bash -x get_schemas_contexts_data.sh
# install dependencies
install:
- pip install -r requirements.txt
# command to run tests
script:
- python setup.py test
branches:
    only:
      - master